RBE 2000 level template code: LabOneCode_2002_Team_09.ino File Reference
LabOneCode_2002_Team_09.ino File Reference
#include "Arduino.h"
#include "ESP32Servo.h"
#include "analogWrite.h"
#include <soc/sens_reg.h>
#include <soc/sens_struct.h>
#include <driver/adc.h>
#include <esp_adc_cal.h>
#include <stdint.h>
#include "esp_types.h"
#include "esp_err.h"
#include "assert.h"
Macros
#define V_REF 1100
Functions
void studentCode ()
int IRAM_ATTR local_adc1_read (int channel)
void complexHandler (void *param)
void IRAM_ATTR onTimer ()
void setup ()
void loop ()
Variables
hw_timer_t * timer = NULL
portMUX_TYPE DRAM_ATTR timerMux = portMUX_INITIALIZER_UNLOCKED
TaskHandle_t complexHandlerTask
uint32_t samplingFreq = 1000
Macro Definition Documentation
#define V_REF 1100
Referenced by setup().
Function Documentation
void complexHandler (void * param)
Definition at line 61 of file LabOneCode_2002_Team_09.ino.
References studentCode().
Referenced by setup().
int IRAM_ATTR local_adc1_read (int channel)
Definition at line 48 of file LabOneCode_2002_Team_09.ino.
Referenced by studentCode().
void loop ()
Definition at line 121 of file LabOneCode_2002_Team_09.ino.
void IRAM_ATTR onTimer ()
Definition at line 69 of file LabOneCode_2002_Team_09.ino.
References complexHandlerTask, and timerMux.
Referenced by setup().
void setup ()
Definition at line 84 of file LabOneCode_2002_Team_09.ino.
References complexHandler(), complexHandlerTask, onTimer(), samplingFreq, timer, and V_REF.
void studentCode ()
Definition at line 34 of file LabOneCode_2002_Team_09.ino.
References local_adc1_read().
Referenced by complexHandler().
Variable Documentation
TaskHandle_t complexHandlerTask
Definition at line 24 of file LabOneCode_2002_Team_09.ino.
Referenced by onTimer(), and setup().
uint32_t samplingFreq = 1000
Definition at line 29 of file LabOneCode_2002_Team_09.ino.
Referenced by setup().
hw_timer_t* timer = NULL
Definition at line 22 of file LabOneCode_2002_Team_09.ino.
Referenced by setup().
portMUX_TYPE DRAM_ATTR timerMux = portMUX_INITIALIZER_UNLOCKED
Definition at line 23 of file LabOneCode_2002_Team_09.ino.
Referenced by onTimer().