RBE 2000 level template code: Waveform_Generator_2002_Team_09.ino File Reference
Waveform_Generator_2002_Team_09.ino File Reference
#include "Arduino.h"
#include "ESP32Servo.h"
#include "analogWrite.h"
#include <soc/sens_reg.h>
#include <soc/sens_struct.h>
#include <driver/adc.h>
#include <esp_adc_cal.h>
#include <stdint.h>
#include "esp_types.h"
#include "esp_err.h"
#include "assert.h"
Functions
void runDDS ()
void complexHandler (void *param)
void IRAM_ATTR onTimer ()
void setup ()
void loop ()
Variables
double interruptCounter50Hz = 0
double interruptCounter1kHz = 0
double sinComp = 0
double sinComp50Hz = 0
double numSamples = 20
double frequencyTarget = 1000
double frequencyTarget2 = 50
int count = (1.0 / (frequencyTarget / 1000000.0)) / numSamples
double increment = (2 * PI) / numSamples
double increment50Hz = increment / (frequencyTarget/frequencyTarget2)
hw_timer_t * timer = NULL
portMUX_TYPE DRAM_ATTR timerMux = portMUX_INITIALIZER_UNLOCKED
TaskHandle_t complexHandlerTask
int oneVoltInAdc = (int)(255.0*(1.0/3.3))
Function Documentation
void complexHandler (void * param)
Definition at line 50 of file Waveform_Generator_2002_Team_09.ino.
References runDDS().
Referenced by setup().
void loop ()
Definition at line 94 of file Waveform_Generator_2002_Team_09.ino.
void IRAM_ATTR onTimer ()
Definition at line 58 of file Waveform_Generator_2002_Team_09.ino.
References complexHandlerTask, and timerMux.
Referenced by setup().
void runDDS ()
Definition at line 33 of file Waveform_Generator_2002_Team_09.ino.
References increment, increment50Hz, interruptCounter1kHz, interruptCounter50Hz, oneVoltInAdc, sinComp, and sinComp50Hz.
Referenced by complexHandler().
void setup ()
Definition at line 73 of file Waveform_Generator_2002_Team_09.ino.
References complexHandler(), complexHandlerTask, count, onTimer(), and timer.
Variable Documentation
TaskHandle_t complexHandlerTask
Definition at line 30 of file Waveform_Generator_2002_Team_09.ino.
Referenced by onTimer(), and setup().
int count = (1.0 / (frequencyTarget / 1000000.0)) / numSamples
Definition at line 24 of file Waveform_Generator_2002_Team_09.ino.
Referenced by setup().
double frequencyTarget = 1000
Definition at line 22 of file Waveform_Generator_2002_Team_09.ino.
double frequencyTarget2 = 50
Definition at line 23 of file Waveform_Generator_2002_Team_09.ino.
double increment = (2 * PI) / numSamples
Definition at line 25 of file Waveform_Generator_2002_Team_09.ino.
Referenced by runDDS().
double increment50Hz = increment / (frequencyTarget/frequencyTarget2)
Definition at line 26 of file Waveform_Generator_2002_Team_09.ino.
Referenced by runDDS().
double interruptCounter1kHz = 0
Definition at line 18 of file Waveform_Generator_2002_Team_09.ino.
Referenced by runDDS().
double interruptCounter50Hz = 0
Definition at line 17 of file Waveform_Generator_2002_Team_09.ino.
Referenced by runDDS().
double numSamples = 20
Definition at line 21 of file Waveform_Generator_2002_Team_09.ino.
int oneVoltInAdc = (int)(255.0*(1.0/3.3))
Definition at line 31 of file Waveform_Generator_2002_Team_09.ino.
Referenced by runDDS().
double sinComp = 0
Definition at line 19 of file Waveform_Generator_2002_Team_09.ino.
Referenced by runDDS().
double sinComp50Hz = 0
Definition at line 20 of file Waveform_Generator_2002_Team_09.ino.
Referenced by runDDS().
hw_timer_t* timer = NULL
Definition at line 28 of file Waveform_Generator_2002_Team_09.ino.
Referenced by setup().
portMUX_TYPE DRAM_ATTR timerMux = portMUX_INITIALIZER_UNLOCKED
Definition at line 29 of file Waveform_Generator_2002_Team_09.ino.
Referenced by onTimer().